name: CI/CD Pipeline

# Trigger this workflow on push to main or pull request to main
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker on the runner
      - name: Set up Docker
        run: sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io -y

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t tennis-game .

      # Step 4: Run the container
      - name: Run the Docker container
        run: docker run tennis-game
